# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: iOS Build for TrollStore

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    name: Build Unsigned iOS App for TrollStore

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set Xcode version
      run: sudo xcode-select -s /Applications/Xcode_15.2.app

    - name: Build MoeMemos for iOS (device)
      run: |
        xcodebuild clean build \
          -project MoeMemos.xcodeproj \
          -scheme MoeMemos \
          -sdk iphoneos \
          -configuration Release \
          CODE_SIGNING_ALLOWED=NO

    - name: Package .app into .ipa
      run: |
        mkdir Payload
        cp -r ~/Library/Developer/Xcode/DerivedData/*/Build/Products/Release-iphoneos/MoeMemos.app Payload/
        zip -r MoeMemos-TrollStore.ipa Payload

    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: MoeMemos-TrollStore-IPA
        path: MoeMemos-TrollStore.ipa
